# NB: This file is for development purposes only!
# Please have proper security for production.

name: bmt-discord-bot

services:
  db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: bmt
      POSTGRES_PASSWORD: bmt
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
