[project]
name = "bmt-discord-bot"
version = "0.1.0"
description = "Discord bot for the Berkeley Math Tournament"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.30.0",
    "asyncpg-stubs>=0.30.1",
    "discord-py>=2.5.2",
]
